### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by masachael** [masachael/chat-space#11]
# IPアドレス
54.238.192.156

**Comment by keisukekodama** [comment]
修正ありがとうございます！
再度確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

①ビューの崩れ
[![Image from Gyazo](https://i.gyazo.com/9ae2f90ba78125dd899673ccd243fbdf.png)](https://gyazo.com/9ae2f90ba78125dd899673ccd243fbdf)

お手本
[![Image from Gyazo](https://i.gyazo.com/93bed3341bbc09ce09f463b23b1bb838.png)](https://gyazo.com/93bed3341bbc09ce09f463b23b1bb838)

[![Image from Gyazo](https://i.gyazo.com/5fa035f4cef1ef3eff2fc7c5a31f5a27.png)](https://gyazo.com/5fa035f4cef1ef3eff2fc7c5a31f5a27)

[![Image from Gyazo](https://i.gyazo.com/0b6f3d0420e08145abc2231df8d9ac16.png)](https://gyazo.com/0b6f3d0420e08145abc2231df8d9ac16)

参考カリキュラム:https://master.tech-camp.in/curriculums/3944


修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by masachael** [comment]
修正しました。

**Comment by yasunamiura** [comment]
河野さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、前回の修正は確認することができました！追加で以下の不備が見受けられましたので修正をお願いします。

- メッセージとメッセージとの間が広いので調整しましょう
[![Image from Gyazo](https://i.gyazo.com/8ca9e794671a621452e0ae12737cce8f.gif)](https://gyazo.com/8ca9e794671a621452e0ae12737cce8f)
見本
[![Image from Gyazo](https://i.gyazo.com/b987db1dd1de7345076c495271a09512.png)](https://gyazo.com/b987db1dd1de7345076c495271a09512)

- 自動更新が正しく動くようにしましょう
※現在は同じメッセージが重複して何度も出てきてしまいます
[![Image from Gyazo](https://i.gyazo.com/215ddde64068fb23034d390f19eb6f19.gif)](https://gyazo.com/215ddde64068fb23034d390f19eb6f19)

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by masachael** [comment]
再度修正しました。

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
